Building DAG of jobs...
Creating conda environment envs/pca.yaml...
Downloading remote packages.
Environment for envs/pca.yaml created (location: .snakemake/conda/570168b1)
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	pca
	2

[Thu Jan 24 13:03:14 2019]
rule pca:
    input: sleuth/sleuth_matrix.csv
    output: plots/pca.svg
    jobid: 1

Activating conda environment: /home/sattle00/Fachprojekt/test/.snakemake/conda/570168b1
[Thu Jan 24 13:03:27 2019]
Error in rule pca:
    jobid: 1
    output: plots/pca.svg
    conda-env: /home/sattle00/Fachprojekt/test/.snakemake/conda/570168b1

RuleException:
CalledProcessError in line 83 of /home/sattle00/Fachprojekt/test/Snakefile:
Command 'source activate /home/sattle00/Fachprojekt/test/.snakemake/conda/570168b1; set -euo pipefail;  python /home/sattle00/Fachprojekt/test/.snakemake/scripts/tmp9xgs0ie0.pca_plot.py ' returned non-zero exit status 1.
  File "/home/sattle00/Fachprojekt/test/Snakefile", line 83, in __rule_pca
  File "/home/sattle00/miniconda3/envs/test/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/sattle00/Fachprojekt/test/.snakemake/log/2019-01-24T125940.282557.snakemake.log
